site: nickwood.io

url: https://www.nickwood.io
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /work/:slug
  notes:
    output: true
    permalink: /notes/:slug    

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "post" 
  -
    scope:
      path: ""
      type: "notes"
    values:
      layout: "post"            

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/work/page:num/"
  